Repository jenkins-infra/plugin-site-api, pull requests merged in 2019-09, with the labels that each got.

#60 [WEBSITE-639] - Missing slash in image URLs
  src/main/java/io/jenkins/plugins/services/impl/GithubExtractor.java
Labels: bug

#64 Add Table of Contents and GitHub Releases badge to README
  README.adoc
Labels: documentation

#65 [WEBSITE-650] Make sure Confluence API extractor uses UTF-8 to avoid broken symbols
  .gitignore
  src/main/java/io/jenkins/plugins/services/impl/HttpClientWikiService.java
  src/test/java/io/jenkins/plugins/services/WikiServiceTest.java
Labels: bug

#66 [WEBSITE-640] - Truncate heading and padding from README pages extracted from GitHub
  src/main/java/io/jenkins/plugins/services/impl/GithubExtractor.java
  src/test/java/io/jenkins/plugins/services/WikiServiceTest.java
Labels: enhancement

#68 Fix the SCM properties in pom.xml
  pom.xml
Labels: chore

#69 [WEBSITE-648] - Add documentation extractor for arbitrary GitHub URLs
  src/main/java/io/jenkins/plugins/services/impl/GithubContentsExtractor.java
  src/main/java/io/jenkins/plugins/services/impl/GithubExtractor.java
  src/main/java/io/jenkins/plugins/services/impl/GithubMatcher.java
  src/main/java/io/jenkins/plugins/services/impl/GithubReadmeExtractor.java
  src/main/java/io/jenkins/plugins/services/impl/HttpClientWikiService.java
  src/main/java/io/jenkins/plugins/web/package-info.java
  src/test/java/io/jenkins/plugins/services/WikiServiceTest.java
Labels: enhancement

#70 Add a Docs SIG Gitter badge to the README
  README.adoc
Labels: documentation

#72 Add a Docker badge to README
  README.adoc
Labels: documentation
