Repository jenkins-infra/plugin-site-api, pull requests merged in 2019-08, with the labels that each got.

#58 [INFRA-2227] - Update Jetty to support debugging with recent Java versions
  pom.xml
Labels: dependencies

#54 [WEBSITE-406] Add special extractors for GitHub and Confluence API
  README.adoc
  src/main/java/io/jenkins/plugins/services/WikiService.java
  src/main/java/io/jenkins/plugins/services/impl/ConfluenceApiExtractor.java
  src/main/java/io/jenkins/plugins/services/impl/ConfluenceDirectExtractor.java
  src/main/java/io/jenkins/plugins/services/impl/GithubExtractor.java
  src/main/java/io/jenkins/plugins/services/impl/HttpClientWikiService.java
  src/main/java/io/jenkins/plugins/services/impl/WikiExtractor.java
  src/test/java/io/jenkins/plugins/services/WikiServiceTest.java
Labels: enhancement

#57 Add support of a local plugins.json.gzip for Development
  README.adoc
  src/main/java/io/jenkins/plugins/services/impl/DefaultConfigurationService.java
Labels: chore
