Repository jenkins-infra/plugin-site-api, pull requests merged in 2023-10, with the labels that each got.

#120 chore(Jenkinsfile) fix failing build
  Jenkinsfile
Labels: chore

#123 chore(Jenkinsfile) do not enable ACP on trusted.ci
  Jenkinsfile
Labels: chore

#122 Removed sentry from the logs
  logback.xml
  pom.xml
  src/main/java/io/jenkins/plugins/RestApp.java
Labels: hacktoberfest-accepted, hacktoberfest

#119 feat: Switch JDK version of the parent image to latest Temurin JDK8
  Dockerfile
Labels: enhancement
